
book:
  网络原理: /network-0
  算法基础: /algorithm-0
  JavaSE: /javase-0
  Android: /android-0
  SPRING: /spring-0
  HIBERNATE: /hibernate-0
  MYBATIS: /mybatis-0
  TODO: /todo-0
 
title: Sorryfu #网站名称
author: Sorryfu
icon: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg

toc:
  max: 3
  min: 2

plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/vs2015.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles