
book:
  无间道: /test1-1
  倩女幽魂: /test2-1
  叶问: /test3-1
 

author: Sorryfu

plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/vs2015.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles